trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: FetchAWSCredentials
  displayName: 'Job 1 - Fetch AWS Credentials from Secrets Manager'
  steps:
  - script: |
      echo "Installing AWS CLI and jq..."
      sudo apt-get update && sudo apt-get install -y awscli jq

      echo "Fetching secret from AWS Secrets Manager..."
      SECRET_JSON=$(aws secretsmanager get-secret-value \
        --secret-id AzurePipelineAWSKeys \
        --query SecretString \
        --output text)

      export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r '.AWS_ACCESS_KEY_ID')
      export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.AWS_SECRET_ACCESS_KEY')

      echo "Configuring AWS CLI..."
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      aws configure set region us-east-1
    displayName: 'Fetch and Configure AWS Credentials'
