trigger:
- main

pool:
  name: Default # Self-hosted agent pool

jobs:
- job: FetchAWSCredentials
  displayName: 'Job 1 - Fetch AWS Credentials from Secrets Manager'
  steps:
  - script: |
      echo "Installing AWS CLI and jq..."
      sudo apt-get update && sudo apt-get install -y awscli jq

      echo "Fetching secret from AWS Secrets Manager..."
      SECRET_JSON=$(aws secretsmanager get-secret-value \
        --secret-id Account-Keys \
        --query SecretString \
        --output text)

      export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r '.AWS_ACCESS_KEY_ID')
      export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.AWS_SECRET_ACCESS_KEY')
      export AWS_DEFAULT_REGION=us-east-1

      echo "Verifying credentials..."
      aws sts get-caller-identity
    displayName: 'Fetch, Export, and Verify AWS Credentials'
